### ISSUE TITLE
jasmine.addMatchers throws error

### ISSUE THREAD

**Issue by sajanchandran** [velesin/jasmine-jquery#197]
After upgrading from 2.1.0 to the latest version of `jasmine-jquery` in my test, and all of my existing tests are failing, with below error

`PhantomJS 1.9.7 (Windows 7) app test country list is loaded successfully FAILED
        TypeError: 'undefined' is not a function (evaluating 'jasmine.addMatchers')
            at C:/workspace-sts-2.3.2.RELEASE/eu.europa.ema.esubmission.psur.ui/psur-ui/src/test/resources/jasmine/jasmine-jquery-2.1.0.js:717`

Any ideas ? any version problem with jquery or jasmine.
